### ISSUE TITLE
Feedback técnico

### ISSUE THREAD

**Issue by Danielalab** [Grecia2727/lim-2018-05-bc-core-am-cipher#7]
Recomendaciones de mejora 👍 
El proyecto cumple con los requerimientos de cifrar, descifrar y pasar el mínimo de tests.
- README: buena idea agregar la organización que tuviste y la idea de prototipos (te recomendamos añadir una imagen para visualizarlo); recuerda que era un requisito agregar quiénes son los principales usuarios de producto y cómo crees que el producto que estás creando les está resolviendo sus problemas.
- Cipher.js: recuerda declarar tus variables en inglés y que estas deben ser descriptivas. Igualmente puedes declarar la siguiente variable (ver imagen) usando **const** ya que no vuelves a reasignarle un valor dentro de la función. 
![image](https://user-images.githubusercontent.com/32286663/41259895-e07b80ae-6d9a-11e8-9af7-e7edb5527d13.png) . Te recomendamos refactorizar tu código y reducir líneas de código repetidas por ejemplo en tu **bucle for** los puedes transformar a un **for ..Of** utilizando EC6; y el bucle que utilizas es igual para encode y decode mas la diferencia esta en la fórmula podríás transformarlo en una función.

- Index.js: Buena idea declarar los elementos del DOM que reutilizas al inicio puedes hacerlo también con la siguiente variable (ver imagen);
![image](https://user-images.githubusercontent.com/32286663/41263145-ad8b8148-6daa-11e8-8b1c-316d3f985a8f.png)
 recuerda que cómo no vueles a reasignarle un nuevo valor a la variables las puedes declarar usando **const**; además debes implementar las funciones de los eventos en EC6 ya que era un requerimiento.
  No olvides declarar tus variables en inglés y que sean descriptivas.
![image](https://user-images.githubusercontent.com/32286663/41263111-78a7c09a-6daa-11e8-9725-85620bc67515.png) 
![image](https://user-images.githubusercontent.com/32286663/41263089-5265850c-6daa-11e8-86b6-ea7cdaec675f.png)

- Css : recuerda mantener una indentación de 2 espacios; te recomendamos utilizar clases para reutilizar estilos repetitivos. Al verlo en versión mobile el formulario es responsive; te recomendamos quitar el scroll horizontal que aparece.
- HTML : recuerda que puedes hacer uso de html semántico y que es mejor agregar estilos a través de css en lugar del mismo html. También debes validar tu html en https://validator.w3.org/nu/?doc=https%3A%2F%2Fgrecia2727.github.io%2Flim-2018-05-bc-core-am-cipher%2Fsrc%2F en este caso muestras 1 warning y 3 errores (ingresar al link para mayor detalle) . En el caso de que desees dejar un espacio para separar etiquetas te recomendamos utilizar **margin o padding** en lugar de la **etiqueta br**.
![image](https://user-images.githubusercontent.com/32286663/41259530-89bb2d2e-6d99-11e8-9940-6e48141ccc8a.png)
![image](https://user-images.githubusercontent.com/32286663/41259637-e99b988c-6d99-11e8-8b45-a69ee8a6bc8c.png)
  Te recomendamos escribir tus id y clases en inglés y no utilizar camel case.
Buen trabajo, sigue asi 👍

**Comment by Grecia2727** [comment]
Gracias :)
